Vue.component('login-box',require('./components/LoginBox').default);
Vue.component('auth-login-box',require('./components/AuthLoginBox').default);
Vue.component('register-detail',require('./components/RegisterDetail').default);
Vue.component('user-edit-father-name',require('./components/UserEditFatherName').default);
Vue.component('user-edit-back-card-number',require('./components/UserBankCart').default);
Vue.component('user-edit-email',require('./components/UserEditEmail').default);
Vue.component('user-edit-national-identity-number',require('./components/UserNationalIdentityNumber').default);
Vue.component('date-of-birth',require('./components/DateOfBirth').default);
Vue.component('auth-register-box',require('./components/AuthRegisterBox').default);
Vue.component('forget-password',require('./components/ForgetPassword').default);
Vue.component('mobile-login-box',require('./components/MobileLoginBox').default);
Vue.component('user-edit-ceremonial-title',require('./components/UserEditCeremonialTitle').default);
Vue.component('user-edit-id-number',require('./components/UserEditIdNumber').default);
Vue.component('user-edit-phone',require('./components/UserEditPhone').default);
Vue.component('user-edit-reagent',require('./components/UserEditReagent').default);
Vue.component('user-edit-introduction',require('./components/UserEditIntroduction').default);
Vue.component('user-edit-description',require('./components/UserEditDescription').default);
Vue.component('list-item-profile',require('./components/ListItemProfile').default);

